spring:
  application:
    name: Storage
server:
  port: 8091
# Eureka服务注册中心
eureka:
  client:
    #服务注册中心的配置内容，指定服务注册中心的位置
    service-url.defaultZone: http://localhost:81/eureka/

---
spring.profiles: s1
spring:
  application:
    name: Storage
server:
  port: 8091
eureka:
  instance:
    hostname: localhost
  client:
    #将当前eureka实例注册到另外一个eureka实例中
    service-url.defaultZone: http://localhost:83/eureka/

---
spring.profiles: s2
spring:
  application:
    name: Storage
server:
  port: 8092
eureka:
  instance:
    hostname: localhost
  client:
    #将当前eureka实例注册到另外一个eureka实例中
    service-url.defaultZone: http://localhost:83/eureka/

---
spring.profiles: s3
spring:
  application:
    name: Storage
server:
  port: 8093
eureka:
  instance:
    hostname: localhost
  client:
    #将当前eureka实例注册到另外一个eureka实例中
    service-url.defaultZone: http://localhost:83/eureka/