spring:
  application:
    name: eureka
server:
  port: 81
# 服务注册中心实例的主机名
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  server:
    enableSelfPreservation: false
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #是否检索服务
    fetch-registry: true
    #服务注册中心的配置内容，指定服务注册中心的位置
    service-url.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring.profiles: s1
spring:
  application:
    name: eureka
server:
  port: 81
eureka:
  instance:
    hostname: localhost
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
#    #是否检索服务
    fetch-registry: true
    #将当前eureka实例注册到另外一个eureka实例中
#    service-url.defaultZone: http://localhost:82/eureka/

---
spring.profiles: s2
spring:
  application:
    name: eureka
server:
  port: 82
eureka:
  instance:
    hostname: localhost
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #是否检索服务
    fetch-registry: true
    #将当前eureka实例注册到另外一个eureka实例中
    service-url.defaultZone: http://localhost:81/eureka/

---
spring.profiles: s3
spring:
  application:
    name: eureka
server:
  port: 83
eureka:
  instance:
    hostname: localhost
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #是否检索服务
    fetch-registry: true
    #将当前eureka实例注册到另外一个eureka实例中
    service-url.defaultZone: http://localhost:82/eureka/